[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
; board = esp32dev
board_build.flash_size = 16MB
; board_build.partitions = partitions_16mb.csv
board_build.arduino.memory_type = qio_opi
framework = arduino
monitor_speed = 115200

lib_deps = 
    bblanchon/ArduinoJson@^6.21.2
    esp32async/AsyncTCP@^3.4.7
    esp32async/ESPAsyncWebServer@^3.8.0
    https://github.com/mavlink/c_library_v2.git
    pstolarz/OneWireNg@^0.14.0

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM
    -DUSB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ASYNC_TCP_STACK_SIZE=8192
    -DCONFIG_ASYNC_TCP_PRIORITY=10

upload_speed = 921600
monitor_filters = 
    esp32_exception_decoder
    time

[env:esp32s2]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
lib_deps = ${env:esp32s3.lib_deps}

build_flags = 
    ${env:esp32s3.build_flags}
    -DBOARD_HAS_PSRAM=0

upload_speed = 921600
monitor_filters = ${env:esp32s3.monitor_filters}

[env:test]
platform = native
test_framework = unity
build_flags =
    -std=c++17
    -DUNITY_INCLUDE_DOUBLE
    -DARDUINO_ARCH_NATIVE
lib_deps =
    throwtheswitch/Unity@^2.5.2