"""Mission Template Static Data

Contains all 42 mission template definitions organized by category.
Templates are static configuration data, not stored in the database.
"""

from typing import Dict, List

from .mission_templates import (
    MissionTemplate,
    TemplateCategory,
    TemplateCategoryInfo,
    TemplateDefaultSettings,
    UserMode,
    WeatherConstraints,
)
from .peripherals import PeripheralType
from .resources import MissionPriority, MissionType, ZoneType


# ============================================================================
# Category Metadata
# ============================================================================

CATEGORY_METADATA: Dict[TemplateCategory, TemplateCategoryInfo] = {
    TemplateCategory.LAWN_CARE: TemplateCategoryInfo(
        category=TemplateCategory.LAWN_CARE,
        name="Lawn Care",
        consumer_name="Lawn Jobs",
        emoji="🌱",
        template_count=6,
        available_count=0,
    ),
    TemplateCategory.FERTILIZATION: TemplateCategoryInfo(
        category=TemplateCategory.FERTILIZATION,
        name="Fertilization & Treatment",
        consumer_name="Feed & Treat",
        emoji="🧪",
        template_count=5,
        available_count=0,
    ),
    TemplateCategory.IRRIGATION: TemplateCategoryInfo(
        category=TemplateCategory.IRRIGATION,
        name="Irrigation",
        consumer_name="Watering",
        emoji="💧",
        template_count=3,
        available_count=0,
    ),
    TemplateCategory.WINTER: TemplateCategoryInfo(
        category=TemplateCategory.WINTER,
        name="Winter Operations",
        consumer_name="Snow & Ice",
        emoji="❄️",
        template_count=5,
        available_count=0,
    ),
    TemplateCategory.CLEANUP: TemplateCategoryInfo(
        category=TemplateCategory.CLEANUP,
        name="Cleanup & Collection",
        consumer_name="Cleanup",
        emoji="🍂",
        template_count=4,
        available_count=0,
    ),
    TemplateCategory.SECURITY: TemplateCategoryInfo(
        category=TemplateCategory.SECURITY,
        name="Security & Patrol",
        consumer_name="Watch & Patrol",
        emoji="👁️",
        template_count=4,
        available_count=0,
    ),
    TemplateCategory.MONITORING: TemplateCategoryInfo(
        category=TemplateCategory.MONITORING,
        name="Environmental Monitoring",
        consumer_name="Yard Health",
        emoji="📊",
        template_count=4,
        available_count=0,
    ),
    TemplateCategory.UTILITY: TemplateCategoryInfo(
        category=TemplateCategory.UTILITY,
        name="Utility & Maintenance",
        consumer_name="Maintenance",
        emoji="🔧",
        template_count=4,
        available_count=0,
    ),
    TemplateCategory.SEASONAL: TemplateCategoryInfo(
        category=TemplateCategory.SEASONAL,
        name="Seasonal Programs",
        consumer_name="Seasonal Care",
        emoji="🗓️",
        template_count=4,
        available_count=0,
    ),
    TemplateCategory.SMART: TemplateCategoryInfo(
        category=TemplateCategory.SMART,
        name="Smart & Adaptive",
        consumer_name="Smart Jobs",
        emoji="🤖",
        template_count=3,
        available_count=0,
    ),
}


# ============================================================================
# Template Definitions - Lawn Care (6)
# ============================================================================

LAWN_CARE_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="basic_mowing",
        name="Basic Mowing",
        consumer_name="Quick Mow",
        description="Standard lawn mowing with configurable height and pattern",
        consumer_description="A quick trim for your lawn",
        emoji="🌱",
        category=TemplateCategory.LAWN_CARE,
        required_peripherals=[PeripheralType.MOWER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=0.5,
            min_temp=5.0,
            max_temp=35.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=5.0,
            mowing_pattern="stripe",
            speed_mode="normal",
            overlap_percentage=10.0,
        ),
        estimated_time_per_acre=45,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="premium_lawn_care",
        name="Premium Lawn Care",
        consumer_name="Full Lawn Service",
        description="Complete lawn care with mowing, edging, and clipping collection",
        consumer_description="The works - mowing, edging, and cleanup",
        emoji="✨",
        category=TemplateCategory.LAWN_CARE,
        required_peripherals=[PeripheralType.MOWER],
        optional_peripherals=[PeripheralType.EDGER, PeripheralType.GRASS_COLLECTOR],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=32.0,
            require_dry_ground=True,
            dry_ground_hours=48,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=4.0,
            mowing_pattern="stripe",
            edge_mode="precise",
            speed_mode="slow",
            overlap_percentage=15.0,
            collection_enabled=True,
        ),
        estimated_time_per_acre=75,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="mulch_and_mow",
        name="Mulch & Mow",
        consumer_name="Natural Fertilizing",
        description="Mowing with mulching for natural fertilization",
        consumer_description="Mow and nourish your lawn naturally",
        emoji="♻️",
        category=TemplateCategory.LAWN_CARE,
        required_peripherals=[PeripheralType.MOWER, PeripheralType.MULCHER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=8.0,
            max_rain_rate=0.0,
            min_temp=15.0,
            max_temp=30.0,
            require_dry_ground=True,
            dry_ground_hours=48,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=6.0,
            mowing_pattern="random",
            speed_mode="slow",
            overlap_percentage=20.0,
            collection_enabled=False,
        ),
        estimated_time_per_acre=55,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        seasons=["spring", "summer"],
    ),
    MissionTemplate(
        id="aeration",
        name="Lawn Aeration",
        consumer_name="Help Lawn Breathe",
        description="Core aeration to improve soil health and root growth",
        consumer_description="Give your lawn room to breathe and grow",
        emoji="🌬️",
        category=TemplateCategory.LAWN_CARE,
        required_peripherals=[PeripheralType.AERATOR],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=2.0,
            min_temp=10.0,
            max_temp=28.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=25.0,
        ),
        estimated_time_per_acre=60,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.NORMAL,
        seasons=["spring", "fall"],
    ),
    MissionTemplate(
        id="overseeding",
        name="Overseeding Mission",
        consumer_name="Grass Renewal",
        description="Aeration followed by overseeding for lawn renovation",
        consumer_description="Thicken up thin spots and renew your lawn",
        emoji="🌾",
        category=TemplateCategory.LAWN_CARE,
        required_peripherals=[PeripheralType.AERATOR, PeripheralType.SEEDER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=8.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=25.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=30.0,
            spread_rate=35.0,  # g/m² for seed
        ),
        estimated_time_per_acre=90,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        seasons=["spring", "fall"],
    ),
    MissionTemplate(
        id="stripe_pattern",
        name="Stripe Pattern Mowing",
        consumer_name="Professional Stripes",
        description="Professional striping pattern for visual appeal",
        consumer_description="Get that pro sports field look",
        emoji="🏟️",
        category=TemplateCategory.LAWN_CARE,
        required_peripherals=[PeripheralType.MOWER],
        optional_peripherals=[PeripheralType.GRASS_COLLECTOR],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=30.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=4.5,
            mowing_pattern="stripe",
            speed_mode="slow",
            overlap_percentage=15.0,
        ),
        estimated_time_per_acre=55,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        seasons=["spring", "summer", "fall"],
    ),
]


# ============================================================================
# Template Definitions - Fertilization & Treatment (5)
# ============================================================================

FERTILIZATION_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="lawn_fertilization",
        name="Lawn Fertilization",
        consumer_name="Feed Your Lawn",
        description="Even fertilizer application across lawn areas",
        consumer_description="Give your lawn the nutrients it needs",
        emoji="🧪",
        category=TemplateCategory.FERTILIZATION,
        required_peripherals=[PeripheralType.FERTILIZER_SPREADER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MOWING, ZoneType.SPRAYING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=8.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=30.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=15.0,
            spread_rate=30.0,  # g/m²
        ),
        estimated_time_per_acre=40,
        default_schedule_type=MissionType.MONTHLY,
        default_priority=MissionPriority.NORMAL,
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="targeted_spraying",
        name="Targeted Spraying",
        consumer_name="Spot Treatment",
        description="Precision chemical/herbicide application",
        consumer_description="Treat problem areas precisely",
        emoji="🎯",
        category=TemplateCategory.FERTILIZATION,
        required_peripherals=[PeripheralType.SPRAYER],
        optional_peripherals=[PeripheralType.CAMERA],
        compatible_zone_types=[ZoneType.SPRAYING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=6.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=28.0,
            require_dry_ground=True,
            dry_ground_hours=48,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=10.0,
            spray_rate=0.05,  # L/m²
        ),
        estimated_time_per_acre=50,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.NORMAL,
        required_feature="precision_spraying",
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="weed_treatment",
        name="Weed Treatment",
        consumer_name="Weed Control",
        description="Camera-guided spot treatment of weeds",
        consumer_description="Find and eliminate weeds",
        emoji="🌿",
        category=TemplateCategory.FERTILIZATION,
        required_peripherals=[PeripheralType.SPRAYER],
        optional_peripherals=[PeripheralType.CAMERA],
        compatible_zone_types=[ZoneType.SPRAYING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=6.0,
            max_rain_rate=0.0,
            min_temp=12.0,
            max_temp=28.0,
            require_dry_ground=True,
            dry_ground_hours=48,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=10.0,
            spray_rate=0.03,  # L/m²
        ),
        estimated_time_per_acre=55,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.NORMAL,
        seasons=["spring", "summer"],
    ),
    MissionTemplate(
        id="pre_emergent",
        name="Pre-Emergent Application",
        consumer_name="Weed Prevention",
        description="Seasonal pre-emergent herbicide application",
        consumer_description="Stop weeds before they start",
        emoji="🛡️",
        category=TemplateCategory.FERTILIZATION,
        required_peripherals=[PeripheralType.SPRAYER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.SPRAYING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=8.0,
            max_rain_rate=0.0,
            min_temp=8.0,
            max_temp=22.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
            overlap_percentage=15.0,
            spray_rate=0.04,  # L/m²
        ),
        estimated_time_per_acre=35,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        seasons=["spring", "fall"],
    ),
    MissionTemplate(
        id="pest_control",
        name="Pest Control",
        consumer_name="Bug Protection",
        description="Insecticide/pesticide application",
        consumer_description="Protect your lawn from pests",
        emoji="🐛",
        category=TemplateCategory.FERTILIZATION,
        required_peripherals=[PeripheralType.SPRAYER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.SPRAYING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=6.0,
            max_rain_rate=0.0,
            min_temp=15.0,
            max_temp=30.0,
            require_dry_ground=True,
            dry_ground_hours=48,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=15.0,
            spray_rate=0.05,  # L/m²
        ),
        estimated_time_per_acre=45,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        seasons=["spring", "summer"],
    ),
]


# ============================================================================
# Template Definitions - Irrigation (3)
# ============================================================================

IRRIGATION_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="smart_watering",
        name="Smart Watering",
        consumer_name="Auto Water",
        description="Sensor-guided irrigation based on moisture levels",
        consumer_description="Water only where and when needed",
        emoji="💧",
        category=TemplateCategory.IRRIGATION,
        required_peripherals=[PeripheralType.SOIL_SENSOR],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.WATERING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=5.0,  # OK to run in light rain
            min_temp=5.0,
            max_temp=40.0,
            require_dry_ground=False,
            require_daylight=False,  # Can run at night
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
        ),
        estimated_time_per_acre=30,
        default_schedule_type=MissionType.DAILY,
        default_priority=MissionPriority.NORMAL,
        required_feature="irrigation",
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="deep_watering",
        name="Deep Watering",
        consumer_name="Root Hydration",
        description="Extended watering for drought recovery",
        consumer_description="Deep soak for stressed lawns",
        emoji="🌊",
        category=TemplateCategory.IRRIGATION,
        required_peripherals=[],  # Vehicle movement only for monitoring
        optional_peripherals=[PeripheralType.SOIL_SENSOR],
        compatible_zone_types=[ZoneType.WATERING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=20.0,
            max_rain_rate=10.0,
            min_temp=10.0,
            max_temp=38.0,
            require_dry_ground=False,
            require_daylight=False,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
        ),
        estimated_time_per_acre=60,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.HIGH,
        required_feature="irrigation",
        seasons=["summer"],
    ),
    MissionTemplate(
        id="new_seed_watering",
        name="New Seed Watering",
        consumer_name="Seed Starter Care",
        description="Light frequent watering for new grass seed",
        consumer_description="Keep new seeds moist for best growth",
        emoji="🌱",
        category=TemplateCategory.IRRIGATION,
        required_peripherals=[PeripheralType.SOIL_SENSOR],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.WATERING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=3.0,
            min_temp=10.0,
            max_temp=30.0,
            require_dry_ground=False,
            require_daylight=False,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
        ),
        estimated_time_per_acre=20,
        default_schedule_type=MissionType.DAILY,
        default_priority=MissionPriority.HIGH,
        required_feature="irrigation",
        seasons=["spring", "fall"],
    ),
]


# ============================================================================
# Template Definitions - Winter Operations (5)
# ============================================================================

WINTER_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="snow_clearing",
        name="Snow Clearing",
        consumer_name="Clear the Snow",
        description="Standard snow removal with snow blower",
        consumer_description="Clear snow from your paths and driveway",
        emoji="❄️",
        category=TemplateCategory.WINTER,
        required_peripherals=[PeripheralType.SNOW_BLOWER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.SNOW_CLEARING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=10.0,
            max_snow_rate=5.0,
            min_temp=-20.0,
            max_temp=5.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            clearing_height=2.0,
            overlap_percentage=20.0,
        ),
        estimated_time_per_acre=60,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        required_feature="snow_clearing",
        seasons=["winter"],
    ),
    MissionTemplate(
        id="heavy_snow",
        name="Heavy Snow Removal",
        consumer_name="Big Storm Cleanup",
        description="Two-pass heavy snow clearing with plow and blower",
        consumer_description="Handle the big storms",
        emoji="🌨️",
        category=TemplateCategory.WINTER,
        required_peripherals=[PeripheralType.SNOW_PLOW, PeripheralType.SNOW_BLOWER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.SNOW_CLEARING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=10.0,
            max_snow_rate=3.0,
            min_temp=-25.0,
            max_temp=2.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            clearing_height=5.0,
            overlap_percentage=25.0,
        ),
        estimated_time_per_acre=90,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.CRITICAL,
        required_feature="snow_clearing",
        seasons=["winter"],
    ),
    MissionTemplate(
        id="de_icing",
        name="De-Icing Application",
        consumer_name="Ice Prevention",
        description="Salt/ice melt application",
        consumer_description="Prevent ice buildup on paths",
        emoji="🧂",
        category=TemplateCategory.WINTER,
        required_peripherals=[PeripheralType.SALT_SPREADER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.SNOW_CLEARING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=5.0,
            min_temp=-15.0,
            max_temp=5.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
            overlap_percentage=15.0,
            spread_rate=50.0,  # g/m² for salt
            salt_application=True,
        ),
        estimated_time_per_acre=30,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        required_feature="snow_clearing",
        seasons=["winter"],
    ),
    MissionTemplate(
        id="full_winter_service",
        name="Full Winter Service",
        consumer_name="Winter Care Package",
        description="Complete snow removal and de-icing",
        consumer_description="Complete winter care - clearing and ice prevention",
        emoji="⛄",
        category=TemplateCategory.WINTER,
        required_peripherals=[
            PeripheralType.SNOW_PLOW,
            PeripheralType.SNOW_BLOWER,
            PeripheralType.SALT_SPREADER,
        ],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.SNOW_CLEARING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=5.0,
            max_snow_rate=2.0,
            min_temp=-20.0,
            max_temp=3.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            clearing_height=3.0,
            overlap_percentage=20.0,
            spread_rate=40.0,
            salt_application=True,
        ),
        estimated_time_per_acre=120,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.CRITICAL,
        required_feature="snow_clearing",
        seasons=["winter"],
    ),
    MissionTemplate(
        id="preventive_salting",
        name="Preventive Salting",
        consumer_name="Pre-Storm Treatment",
        description="Pre-storm salt application",
        consumer_description="Get ahead of the storm",
        emoji="🌬️",
        category=TemplateCategory.WINTER,
        required_peripherals=[PeripheralType.SALT_SPREADER],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.SNOW_CLEARING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=2.0,
            min_temp=-10.0,
            max_temp=5.0,
            require_dry_ground=True,
            dry_ground_hours=6,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
            overlap_percentage=10.0,
            spread_rate=30.0,
            salt_application=True,
        ),
        estimated_time_per_acre=25,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        required_feature="snow_clearing",
        seasons=["winter"],
    ),
]


# ============================================================================
# Template Definitions - Cleanup & Collection (4)
# ============================================================================

CLEANUP_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="leaf_collection",
        name="Leaf Collection",
        consumer_name="Fall Cleanup",
        description="Autumn leaf cleanup with blower, vacuum, and collector",
        consumer_description="Clear all those fallen leaves",
        emoji="🍂",
        category=TemplateCategory.CLEANUP,
        required_peripherals=[PeripheralType.LEAF_BLOWER],
        optional_peripherals=[PeripheralType.VACUUM, PeripheralType.DEBRIS_COLLECTOR],
        compatible_zone_types=[ZoneType.COLLECTION, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=8.0,
            max_rain_rate=0.5,
            min_temp=5.0,
            max_temp=25.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=20.0,
            collection_enabled=True,
        ),
        estimated_time_per_acre=70,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        required_feature="debris_collection",
        seasons=["fall"],
    ),
    MissionTemplate(
        id="debris_patrol",
        name="Debris Patrol",
        consumer_name="Quick Cleanup",
        description="General debris collection",
        consumer_description="Pick up sticks, debris, and small items",
        emoji="🧹",
        category=TemplateCategory.CLEANUP,
        required_peripherals=[PeripheralType.VACUUM],
        optional_peripherals=[PeripheralType.DEBRIS_COLLECTOR],
        compatible_zone_types=[ZoneType.COLLECTION, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=0.5,
            min_temp=5.0,
            max_temp=35.0,
            require_dry_ground=True,
            dry_ground_hours=12,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
            overlap_percentage=15.0,
            collection_enabled=True,
        ),
        estimated_time_per_acre=40,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.LOW,
        required_feature="debris_collection",
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="post_storm",
        name="Post-Storm Cleanup",
        consumer_name="Storm Recovery",
        description="Storm damage debris removal",
        consumer_description="Clean up after storms",
        emoji="🌪️",
        category=TemplateCategory.CLEANUP,
        required_peripherals=[PeripheralType.DEBRIS_COLLECTOR],
        optional_peripherals=[PeripheralType.VACUUM],
        compatible_zone_types=[ZoneType.COLLECTION, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=2.0,
            min_temp=5.0,
            max_temp=35.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=25.0,
            collection_enabled=True,
        ),
        estimated_time_per_acre=80,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        required_feature="debris_collection",
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="grass_clipping_collection",
        name="Grass Clipping Collection",
        consumer_name="Clipping Pickup",
        description="Collect clippings after mowing",
        consumer_description="Pick up grass clippings",
        emoji="🌿",
        category=TemplateCategory.CLEANUP,
        required_peripherals=[PeripheralType.GRASS_COLLECTOR],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=32.0,
            require_dry_ground=True,
            dry_ground_hours=12,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
            overlap_percentage=15.0,
            collection_enabled=True,
        ),
        estimated_time_per_acre=35,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.LOW,
        seasons=["spring", "summer", "fall"],
    ),
]


# ============================================================================
# Template Definitions - Security & Patrol (4)
# ============================================================================

SECURITY_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="perimeter_patrol",
        name="Perimeter Patrol",
        consumer_name="Property Watch",
        description="Security patrol with recording",
        consumer_description="Keep an eye on your property",
        emoji="👁️",
        category=TemplateCategory.SECURITY,
        required_peripherals=[PeripheralType.CAMERA],
        optional_peripherals=[PeripheralType.LIGHTING],
        compatible_zone_types=[ZoneType.PATROL],
        weather_constraints=WeatherConstraints(
            max_wind_speed=20.0,
            max_rain_rate=10.0,
            min_temp=-10.0,
            max_temp=40.0,
            require_dry_ground=False,
            require_daylight=False,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            dwell_time=10,
            motion_detection=True,
            recording=True,
        ),
        estimated_time_per_acre=30,
        default_schedule_type=MissionType.DAILY,
        default_priority=MissionPriority.NORMAL,
        required_feature="security_patrol",
    ),
    MissionTemplate(
        id="night_watch",
        name="Night Watch",
        consumer_name="Overnight Security",
        description="Nighttime surveillance patrol",
        consumer_description="Watch over your property at night",
        emoji="🌙",
        category=TemplateCategory.SECURITY,
        required_peripherals=[PeripheralType.CAMERA, PeripheralType.LIGHTING],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.PATROL],
        weather_constraints=WeatherConstraints(
            max_wind_speed=20.0,
            max_rain_rate=10.0,
            min_temp=-15.0,
            max_temp=35.0,
            require_dry_ground=False,
            require_daylight=False,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            dwell_time=15,
            motion_detection=True,
            recording=True,
        ),
        estimated_time_per_acre=40,
        default_schedule_type=MissionType.DAILY,
        default_priority=MissionPriority.HIGH,
        required_feature="security_patrol",
    ),
    MissionTemplate(
        id="motion_response",
        name="Motion Response",
        consumer_name="Activity Check",
        description="Respond to motion detection alerts",
        consumer_description="Check on detected movement",
        emoji="🚨",
        category=TemplateCategory.SECURITY,
        required_peripherals=[PeripheralType.CAMERA, PeripheralType.LIGHTING],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.PATROL],
        weather_constraints=WeatherConstraints(
            max_wind_speed=25.0,
            max_rain_rate=15.0,
            min_temp=-20.0,
            max_temp=45.0,
            require_dry_ground=False,
            require_daylight=False,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="fast",
            dwell_time=30,
            motion_detection=True,
            recording=True,
        ),
        estimated_time_per_acre=15,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.CRITICAL,
        required_feature="security_patrol",
    ),
    MissionTemplate(
        id="property_survey",
        name="Property Survey",
        consumer_name="Full Property Scan",
        description="Complete property documentation with camera and lidar",
        consumer_description="Full scan and record of your property",
        emoji="📸",
        category=TemplateCategory.SECURITY,
        required_peripherals=[PeripheralType.CAMERA],
        optional_peripherals=[PeripheralType.LIDAR],
        compatible_zone_types=[ZoneType.PATROL, ZoneType.MONITORING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=2.0,
            min_temp=5.0,
            max_temp=35.0,
            min_visibility=5000,
            require_dry_ground=True,
            dry_ground_hours=12,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            dwell_time=5,
            recording=True,
        ),
        estimated_time_per_acre=50,
        default_schedule_type=MissionType.MONTHLY,
        default_priority=MissionPriority.LOW,
        required_feature="security_patrol",
    ),
]


# ============================================================================
# Template Definitions - Environmental Monitoring (4)
# ============================================================================

MONITORING_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="soil_health",
        name="Soil Health Check",
        consumer_name="Soil Testing",
        description="Comprehensive soil analysis with sensors",
        consumer_description="Check your soil's health",
        emoji="🌍",
        category=TemplateCategory.MONITORING,
        required_peripherals=[PeripheralType.SOIL_SENSOR],
        optional_peripherals=[PeripheralType.ENVIRONMENTAL_SENSOR],
        compatible_zone_types=[ZoneType.MONITORING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=5.0,
            min_temp=5.0,
            max_temp=35.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=30.0,
        ),
        estimated_time_per_acre=45,
        default_schedule_type=MissionType.MONTHLY,
        default_priority=MissionPriority.LOW,
        required_feature="environmental_monitoring",
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="weather_station_patrol",
        name="Weather Station Patrol",
        consumer_name="Sensor Check",
        description="Collect environmental data across property",
        consumer_description="Check conditions around your yard",
        emoji="🌡️",
        category=TemplateCategory.MONITORING,
        required_peripherals=[PeripheralType.ENVIRONMENTAL_SENSOR],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MONITORING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=25.0,
            max_rain_rate=15.0,
            min_temp=-15.0,
            max_temp=45.0,
            require_dry_ground=False,
            require_daylight=False,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
            dwell_time=30,
        ),
        estimated_time_per_acre=25,
        default_schedule_type=MissionType.DAILY,
        default_priority=MissionPriority.LOW,
        required_feature="environmental_monitoring",
    ),
    MissionTemplate(
        id="moisture_mapping",
        name="Moisture Mapping",
        consumer_name="Water Level Check",
        description="Create soil moisture map",
        consumer_description="Find dry and wet spots",
        emoji="💦",
        category=TemplateCategory.MONITORING,
        required_peripherals=[PeripheralType.SOIL_SENSOR],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.MONITORING, ZoneType.WATERING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=35.0,
            require_dry_ground=True,
            dry_ground_hours=12,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=40.0,
        ),
        estimated_time_per_acre=55,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        required_feature="environmental_monitoring",
        seasons=["spring", "summer"],
    ),
    MissionTemplate(
        id="microclimate_analysis",
        name="Microclimate Analysis",
        consumer_name="Environment Scan",
        description="Identify microclimates in yard",
        consumer_description="Find the different climate zones in your yard",
        emoji="🔬",
        category=TemplateCategory.MONITORING,
        required_peripherals=[PeripheralType.ENVIRONMENTAL_SENSOR],
        optional_peripherals=[PeripheralType.CAMERA],
        compatible_zone_types=[ZoneType.MONITORING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=30.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            dwell_time=60,
        ),
        estimated_time_per_acre=90,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.LOW,
        required_feature="environmental_monitoring",
        seasons=["summer"],
    ),
]


# ============================================================================
# Template Definitions - Utility & Maintenance (4)
# ============================================================================

UTILITY_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="battery_conditioning",
        name="Battery Conditioning",
        consumer_name="Battery Health",
        description="Return to charge and condition battery",
        consumer_description="Keep your battery healthy",
        emoji="🔋",
        category=TemplateCategory.UTILITY,
        required_peripherals=[PeripheralType.POWER_MODULE],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.CHARGING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=25.0,
            max_rain_rate=10.0,
            min_temp=-10.0,
            max_temp=40.0,
            require_dry_ground=False,
            require_daylight=False,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
        ),
        estimated_time_per_acre=5,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.LOW,
        min_user_mode=UserMode.POWER_USER,
    ),
    MissionTemplate(
        id="equipment_check",
        name="Equipment Check",
        consumer_name="System Test",
        description="Visual inspection of yard and equipment",
        consumer_description="Make sure everything is working",
        emoji="🔍",
        category=TemplateCategory.UTILITY,
        required_peripherals=[PeripheralType.CAMERA],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.STAGING, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=5.0,
            min_temp=0.0,
            max_temp=40.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            dwell_time=10,
            recording=True,
        ),
        estimated_time_per_acre=20,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.LOW,
        min_user_mode=UserMode.POWER_USER,
    ),
    MissionTemplate(
        id="boundary_mapping",
        name="Boundary Mapping",
        consumer_name="Property Mapping",
        description="Map and verify property boundaries",
        consumer_description="Map your property boundaries",
        emoji="🗺️",
        category=TemplateCategory.UTILITY,
        required_peripherals=[PeripheralType.LIDAR],
        optional_peripherals=[PeripheralType.CAMERA],
        compatible_zone_types=[ZoneType.EXCLUSION, ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=0.5,
            min_temp=5.0,
            max_temp=35.0,
            min_visibility=5000,
            require_dry_ground=True,
            dry_ground_hours=12,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=50.0,
        ),
        estimated_time_per_acre=60,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.NORMAL,
        min_user_mode=UserMode.POWER_USER,
    ),
    MissionTemplate(
        id="material_transport",
        name="Material Transport",
        consumer_name="Hauling",
        description="Move materials between staging areas",
        consumer_description="Transport materials around your yard",
        emoji="🚚",
        category=TemplateCategory.UTILITY,
        required_peripherals=[PeripheralType.TRAILER_HITCH],
        optional_peripherals=[],
        compatible_zone_types=[ZoneType.STAGING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=5.0,
            min_temp=-5.0,
            max_temp=38.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
        ),
        estimated_time_per_acre=30,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.NORMAL,
        min_user_mode=UserMode.POWER_USER,
    ),
]


# ============================================================================
# Template Definitions - Seasonal Programs (4)
# ============================================================================

SEASONAL_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="spring_startup",
        name="Spring Startup",
        consumer_name="Wake Up Routine",
        description="Complete spring lawn preparation: aeration + overseeding + fertilization",
        consumer_description="Get your lawn ready for the growing season",
        emoji="🌸",
        category=TemplateCategory.SEASONAL,
        required_peripherals=[PeripheralType.AERATOR],
        optional_peripherals=[PeripheralType.SEEDER, PeripheralType.FERTILIZER_SPREADER],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=25.0,
            require_dry_ground=True,
            dry_ground_hours=48,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=25.0,
            spread_rate=35.0,
        ),
        estimated_time_per_acre=120,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        seasons=["spring"],
    ),
    MissionTemplate(
        id="summer_maintenance",
        name="Summer Maintenance",
        consumer_name="Hot Weather Care",
        description="Hot weather lawn care: mowing + watering",
        consumer_description="Keep your lawn healthy in the heat",
        emoji="☀️",
        category=TemplateCategory.SEASONAL,
        required_peripherals=[PeripheralType.MOWER],
        optional_peripherals=[PeripheralType.SOIL_SENSOR],
        compatible_zone_types=[ZoneType.MOWING, ZoneType.WATERING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=0.5,
            min_temp=20.0,
            max_temp=38.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=7.0,  # Higher in summer
            mowing_pattern="stripe",
            speed_mode="normal",
            overlap_percentage=10.0,
        ),
        estimated_time_per_acre=50,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        seasons=["summer"],
    ),
    MissionTemplate(
        id="fall_prep",
        name="Fall Preparation",
        consumer_name="Autumn Ready",
        description="Prepare lawn for winter: leaf collection + aeration + fertilization",
        consumer_description="Get your lawn ready for winter",
        emoji="🍁",
        category=TemplateCategory.SEASONAL,
        required_peripherals=[PeripheralType.LEAF_BLOWER],
        optional_peripherals=[
            PeripheralType.AERATOR,
            PeripheralType.FERTILIZER_SPREADER,
            PeripheralType.DEBRIS_COLLECTOR,
        ],
        compatible_zone_types=[ZoneType.MOWING, ZoneType.COLLECTION],
        weather_constraints=WeatherConstraints(
            max_wind_speed=8.0,
            max_rain_rate=0.5,
            min_temp=5.0,
            max_temp=20.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="slow",
            overlap_percentage=20.0,
            collection_enabled=True,
            spread_rate=40.0,
        ),
        estimated_time_per_acre=100,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        required_feature="debris_collection",
        seasons=["fall"],
    ),
    MissionTemplate(
        id="winter_ready",
        name="Winterization",
        consumer_name="Winter Prep",
        description="End of season preparation: final mow + cleanup + equipment check",
        consumer_description="Prepare for winter",
        emoji="🥶",
        category=TemplateCategory.SEASONAL,
        required_peripherals=[PeripheralType.MOWER],
        optional_peripherals=[PeripheralType.VACUUM, PeripheralType.CAMERA],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=0.5,
            min_temp=2.0,
            max_temp=15.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=3.0,  # Lower final cut
            mowing_pattern="stripe",
            speed_mode="slow",
            overlap_percentage=15.0,
            collection_enabled=True,
        ),
        estimated_time_per_acre=70,
        default_schedule_type=MissionType.ONCE,
        default_priority=MissionPriority.HIGH,
        seasons=["fall"],
    ),
]


# ============================================================================
# Template Definitions - Smart & Adaptive (3)
# ============================================================================

SMART_TEMPLATES: List[MissionTemplate] = [
    MissionTemplate(
        id="adaptive_mowing",
        name="Adaptive Mowing",
        consumer_name="Smart Mowing",
        description="Adjust mowing height based on grass condition",
        consumer_description="Mows smarter based on grass health",
        emoji="🤖",
        category=TemplateCategory.SMART,
        required_peripherals=[PeripheralType.MOWER, PeripheralType.CAMERA],
        optional_peripherals=[PeripheralType.SOIL_SENSOR],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=10.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=32.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=5.0,
            mowing_pattern="stripe",
            speed_mode="normal",
            overlap_percentage=15.0,
        ),
        estimated_time_per_acre=55,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        min_user_mode=UserMode.POWER_USER,
        seasons=["spring", "summer", "fall"],
    ),
    MissionTemplate(
        id="weather_responsive",
        name="Weather-Responsive Care",
        consumer_name="Weather-Smart Care",
        description="Adjust operations based on weather forecasts",
        consumer_description="Adapts to the weather automatically",
        emoji="🌤️",
        category=TemplateCategory.SMART,
        required_peripherals=[PeripheralType.ENVIRONMENTAL_SENSOR],
        optional_peripherals=[PeripheralType.MOWER, PeripheralType.SPRAYER],
        compatible_zone_types=[ZoneType.MOWING, ZoneType.MONITORING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=15.0,
            max_rain_rate=5.0,
            min_temp=5.0,
            max_temp=38.0,
            require_dry_ground=False,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            speed_mode="normal",
        ),
        estimated_time_per_acre=40,
        default_schedule_type=MissionType.DAILY,
        default_priority=MissionPriority.NORMAL,
        min_user_mode=UserMode.POWER_USER,
    ),
    MissionTemplate(
        id="growth_based",
        name="Growth-Based Schedule",
        consumer_name="Grass Growth Tracking",
        description="Mow based on detected grass growth",
        consumer_description="Mows when your grass needs it",
        emoji="📈",
        category=TemplateCategory.SMART,
        required_peripherals=[PeripheralType.CAMERA, PeripheralType.MOWER],
        optional_peripherals=[PeripheralType.SOIL_SENSOR],
        compatible_zone_types=[ZoneType.MOWING],
        weather_constraints=WeatherConstraints(
            max_wind_speed=12.0,
            max_rain_rate=0.0,
            min_temp=10.0,
            max_temp=32.0,
            require_dry_ground=True,
            dry_ground_hours=24,
            require_daylight=True,
        ),
        default_settings=TemplateDefaultSettings(
            mowing_height=5.0,
            mowing_pattern="stripe",
            speed_mode="normal",
            overlap_percentage=10.0,
        ),
        estimated_time_per_acre=50,
        default_schedule_type=MissionType.WEEKLY,
        default_priority=MissionPriority.NORMAL,
        min_user_mode=UserMode.POWER_USER,
        seasons=["spring", "summer", "fall"],
    ),
]


# ============================================================================
# Combined Template List
# ============================================================================

ALL_TEMPLATES: List[MissionTemplate] = (
    LAWN_CARE_TEMPLATES
    + FERTILIZATION_TEMPLATES
    + IRRIGATION_TEMPLATES
    + WINTER_TEMPLATES
    + CLEANUP_TEMPLATES
    + SECURITY_TEMPLATES
    + MONITORING_TEMPLATES
    + UTILITY_TEMPLATES
    + SEASONAL_TEMPLATES
    + SMART_TEMPLATES
)

# Template lookup by ID
TEMPLATES_BY_ID: Dict[str, MissionTemplate] = {t.id: t for t in ALL_TEMPLATES}

# Templates grouped by category
TEMPLATES_BY_CATEGORY: Dict[TemplateCategory, List[MissionTemplate]] = {
    TemplateCategory.LAWN_CARE: LAWN_CARE_TEMPLATES,
    TemplateCategory.FERTILIZATION: FERTILIZATION_TEMPLATES,
    TemplateCategory.IRRIGATION: IRRIGATION_TEMPLATES,
    TemplateCategory.WINTER: WINTER_TEMPLATES,
    TemplateCategory.CLEANUP: CLEANUP_TEMPLATES,
    TemplateCategory.SECURITY: SECURITY_TEMPLATES,
    TemplateCategory.MONITORING: MONITORING_TEMPLATES,
    TemplateCategory.UTILITY: UTILITY_TEMPLATES,
    TemplateCategory.SEASONAL: SEASONAL_TEMPLATES,
    TemplateCategory.SMART: SMART_TEMPLATES,
}


def get_template_by_id(template_id: str) -> MissionTemplate | None:
    """Get a template by its ID"""
    return TEMPLATES_BY_ID.get(template_id)


def get_templates_by_category(category: TemplateCategory) -> List[MissionTemplate]:
    """Get all templates in a category"""
    return TEMPLATES_BY_CATEGORY.get(category, [])


def get_all_templates() -> List[MissionTemplate]:
    """Get all templates"""
    return ALL_TEMPLATES.copy()


def get_category_metadata() -> Dict[TemplateCategory, TemplateCategoryInfo]:
    """Get category metadata"""
    return CATEGORY_METADATA.copy()
